# Generated by Django 4.0.3 on 2022-09-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.ImageField(height_field='H', max_length=20, null=True, upload_to='', width_field='w'),
        ),
    ]
