# Generated by Django 4.0.3 on 2022-09-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to=''),
        ),
    ]
